export const ZERO_COMMISSION: number = 0;
export const TAKE_COMMISSION_TIMES: number = 2;


export enum AliveBotErrorPlace {
  ACCOUNT_AMOUNT_UPDATE = 'ACCOUNT_AMOUNT_UPDATE',
  MARKET_WS_CLOSE = 'MARKET_WS_CLOSE',
  MARKET_WS_ERROR = 'MARKET_WS_ERROR',
  POSITION_CLOSE = 'POSITION_CLOSE'
}
