export const RESTART_BOT_COUNT_LIMIT: number = 3;


export enum BotErrorPlace {
  BOT_CREATE = 'BOT_CREATE',
  ACCOUNT_AMOUNT_UPDATE = 'ACCOUNT_AMOUNT_UPDATE',
  MARKET_WS_CLOSE = 'MARKET_WS_CLOSE',
  MARKET_WS_ERROR = 'MARKET_WS_ERROR',
  POSITION_OPEN = 'POSITION_OPEN',
  POSITION_CLOSE = 'POSITION_CLOSE'
}
