export enum AliveBotErrorPlace {
  ACCOUNT_AMOUNT_UPDATE = 'ACCOUNT_AMOUNT_UPDATE',
  MARKET_WS_CLOSE = 'MARKET_WS_CLOSE',
  MARKET_WS_ERROR = 'MARKET_WS_ERROR',
  POSITION_CLOSE = 'POSITION_CLOSE'
}
